### ISSUE TITLE
[rich-text-react-renderer] BLOCKS.DOCUMENT in options.renderNode is ignored

### ISSUE THREAD

**Issue by Simon-Tang** [contentful/rich-text#104]
Hi team,

The `rich-text-react-renderer` package is really cool! However I've noticed that although the README does list `BLOCKS.DOCUMENT`, this package doesn't allow the user to wrap the rendered output with an option like the following:

```
documentToReactComponents(
  json,
  {
    renderNode: {
      [BLOCKS.DOCUMENT]: (node, children) => (
        <CustomWrapper>{children}</CustomWrapper>
      ),
    },
  },
);
```

Maybe we could add this functionality by passing the root node itself into [`nodeToReactComponent`](https://github.com/contentful/rich-text/blob/dbda9fc5cc7de40b47218fefbe3d7c2d2f8d3024/packages/rich-text-react-renderer/src/util/nodeListToReactComponents.tsx#L14)?

**Comment by sbezludny** [comment]
Sounds good to me, feel free to open a PR :)
