### ISSUE TITLE
rich-text-from-markdown plugin not working in IE 11

### ISSUE THREAD

**Issue by khus29** [contentful/rich-text#107]
rich-text-from-markdown is returning null data after processing in IE 11. It is working fine in other browsers including IE edge. Below is the code snippet 
`function processRichtext() {

        var markup = $('span[role="presentation"]').text(); // getting this value;
        var document = rtObj.richTextFromMarkdown(markup).then(function (markdown) {
           
            //here markdown value is null in IE 11
            $("#hdnRte").val(JSON.stringify(markdown));
        });
    }`
Looks like this issue is related to plugin. 
Please help.

**Comment by sbezludny** [comment]
Hey @khus29,
When we were creating `rich-text-from-markdown` library, the primary use-case was to use it in the migration scripts which run in the node environment, and therefore we did not optimize it for the browsers. 
Feel free to create a PR to fix that. I will try to provide as much information as I can to help you with that.
