### ISSUE TITLE
Make code block visually more different & add code block

### ISSUE THREAD

**Issue by lukasoppermann** [contentful/rich-text#113]
The visual difference between code blocks and text in the editor is very small. It would make it much easier for authors if you would e.g. add a light grey bg color or something like this.

Additionally it would be very helpful to allow for a code block as well and not just an inline code tag.

**Comment by larimaza** [comment]
@lukasoppermann Hello, may I ask why this issue was closed? Coincidentally I was just trying to implement code blocks and noticed I couldn't because `MARKS.CODE` renders a `<code>` element and that's for inline only.
Does this library have support for blocks that I may have missed?

**Comment by lukasoppermann** [comment]
Hey @larimaza, I am not using contentful anymore myself and it seems to be a stale. No comment from contentful since opening it nearly 3 years ago.

That is why I closed it, as I have no stakes in it anymore and I am trying to clean up my open issues a bit. 😉 

Maybe you can open a new ticket with your use case. It might get more attention.
