### ISSUE TITLE
Possible to turn off localization?

### ISSUE THREAD

**Issue by aofolts** [contentful/rich-text#115]
When I receive data in `gatsby-source-contentful` the fields are normal...

```
{
  title: "Example"
}
```

But when I use `rich-text`, the fields are nested, like so...

```
{
  fields {
    title: {
      "en-US": "Example"
    }
  }
}
```

I have localization turned off, so why am I receiving localized data?

Is there any way to prevent this in `rich-text`?

**Comment by sbezludny** [comment]
Hey, 
It seems that `gatsby-source-contentful` does not normalize resolved entries in rich text documents. We do not maintain this plugin ourselves. Thus,  I would recommend opening an issue in gatsby repo. 
Please let me know if there is anything else we can do to help you.

**Comment by aofolts** [comment]
@sbezludny So the standard for Contentful is to nest inside fields and use localization whether you have it turned on or not?

Just wondering because I'm never going to translate my blog, so it's a pain to keep destructuring `fields` and `en-US`. It would be nice to be able to opt out of this, but I can easily write a normalizing function if not.

**Comment by aofolts** [comment]
Just revisited the `gatsby-source-contentful` documentation and there's actually a locale option. Would be nice if Contentful had that with `rich-text`:

`localeFilter [function][optional] [default: () => true]`

Possibility to limit how many locales/nodes are created in graphQL. This can limit the memory usage by reducing the amount of nodes created. Useful if you have a large space in contentful and only want to get the data from one selected locale.

For example, to filter locales on only `germany localeFilter: locale => locale.code === 'de-DE'`

**Comment by bsgreenb** [comment]
@aofolts Did you ever find a solution that removes the localization keys?

**Comment by aofolts** [comment]
@bsgreenb I just wrote a normalizing function that I use everywhere I'm passing down Contentful data. The function drills down recursively and removes any localization. It's not ideal but gets the job done.

**Comment by bsgreenb** [comment]
@aofolts This is even more of a hassle in TypeScript:

```
export type ContentfulCardEmbed = {
  fields: {
    title: {
      "en-US": string;
    };
    body: {
      "en-US": Document;
    };
    entity: {
      "en-US": {
        fields: {
          title: {
            "en-US": string;
          };
          featuredImage: {
            "en-US": {
              fields: {
                file: {
                  "en-US": {
                    url: string;
                  };
                };
              };
            };
          };
        };
      };
    };
  };
};
```

**Comment by aofolts** [comment]
@bsgreenb Yea, that's brutal. Most projects don't need localization, so it doesn't make sense to burden everyone with localization. All that needs to be done is to provide support for a localization option in `gatsby-config`.

**Comment by vandelay87** [comment]
Yeah, having the option to turn off location would be ideal. It also wraps props in a 'fields' object which isn't great when rendering components dynamically and spreading the props.

I had to go through the fields recursively and remove them. I could improve this so that instead of reassigning function parameters it builds the clean fields dynamically, but I'm yet to get round to it.

For anyone looking for a quick solution:

First I destructure the props:

`const { fields } = node.data.target;`

Then I clean the object by passing the fields to the following function:

```
const cleanProperties = (dirtyObj) => {
    const cleanObj = JSON.parse(JSON.stringify(dirtyObj));
    const locale = 'en-GB';
  
    const deepObjectLoop = (obj) => {
      Object.keys(obj).forEach(key => {
        if (obj[key] && typeof obj[key][locale] !== 'undefined') {
          const localeValue = obj[key][locale];
  
          delete obj[key][locale];
          obj[key] = localeValue;
        }
  
        if (obj[key] && typeof obj[key].sys !== 'undefined' 
        && typeof obj[key].sys.id !== 'undefined') {
          const idValue = obj[key].sys.id;
  
          delete obj[key].sys;
          obj[key].id = idValue;
        }
  
        if (obj[key] && typeof obj[key].fields !== 'undefined') {
          const localeValue = obj[key].fields;
          const idValue = obj[key].id;
  
          delete obj[key].fields;
          obj[key] = localeValue;
  
          if (idValue !== 'undefined') {
            obj[key].id = idValue;
          }
        }
  
        if (typeof obj[key] === 'object') {
          deepObjectLoop(obj[key]);
        }
      });
    }

    deepObjectLoop(cleanObj);
    return cleanObj;
  }
```

**Comment by zolk** [comment]
This is now a feature in `gatsby-source-contentful`. You can pass in the following option and the locale nodes will no longer be present in rich text fields.

```js
richText: {
  resolveFieldLocales: true
}
```

**Comment by bsgreenb** [comment]
Thank you @zolk!
