### ISSUE TITLE
ASSET_HYPERLINK is not rendered properly

### ISSUE THREAD

**Issue by finnp** [contentful/rich-text#118]
Hyper link assets are rendered like this by default in the react renderer:
![image](https://user-images.githubusercontent.com/841788/66638316-fa0a7080-ec14-11e9-9c7e-daf5c1f98459.png)

They should be rendered as shown in the rich text editor, as links.

**Comment by tom-curphey** [comment]
Just solved this with my ContentfulRichText.tsx file where <Link/> is a customer built component for handling links..

However the main part is getting the data you wanted to display..
Hope this makes sense?

`    [INLINES.ASSET_HYPERLINK]: (node: any, children: any) => {
      return (
        <Link
          to={
            node.data && node.data.target.fields.file[locale].url
              ? node.data.target.fields.file[locale].url
              : null
          }
        >
          {children}
        </Link>
      )
    },`

**Comment by Khaledgarbaya** [comment]
Hi @finnp,
Since asset-hyperlink can be anything binary, we don't do a default rendering.
you need to do what @tom-curphey suggested.
