### ISSUE TITLE
[rich-text-from-markdown] Could not find a declaration file for module

### ISSUE THREAD

**Issue by teramotodaiki** [contentful/rich-text#128]
Using `@contentful/rich-text-from-markdown` with TypeScript causes an error.

```
Could not find a declaration file for module '@contentful/rich-text-from-markdown'. '{PATH}/node_modules/@contentful/rich-text-from-markdown/dist/rich-text-from-markdown.es5.js' implicitly has an 'any' type.
  Try `npm install @types/contentful__rich-text-from-markdown` if it exists or add a new declaration (.d.ts) file containing `declare module '@contentful/rich-text-from-markdown';`ts(7016)
```

Other packages such as `@contentful/rich-text-react-renderer` do not cause this error and these provide type definitions. This is a bit strange because both are written in TypeScript.

## Reproduce

You can see this error on [codesandbox.io](https://codesandbox.io/s/trusting-davinci-p2c6m). A red underline is under package name.

## Solution

I compared `@contentful/rich-text-from-markdown` and `@contentful/rich-text-react-renderer`, `@contentful/rich-text-from-markdown` does not have property `"typings"` in the [package.json](https://github.com/contentful/rich-text/blob/master/packages/rich-text-from-markdown/package.json).

In the node_modules, this package has `dist/types/index.d.ts`. It looks correct type definition.

```dist/types/index.d.ts
import { Document, Node } from '@contentful/rich-text-types';
import { MarkdownNode } from './types';
export declare type FallbackResolver = (mdNode: MarkdownNode) => Promise<Node | Node[] | null>;
export declare function richTextFromMarkdown(md: string, fallback?: FallbackResolver): Promise<Document>;
```

So I think that inserting `"typings": "dist/types/index.d.ts"` into package.json and publish again to resolve this problem. I could make pull request if needed.

**Comment by msholty-fd** [comment]
@teramotodaiki - I think you can work around this on your end if you add something like this to your project:
```ts
declare module '@contentful/rich-text-from-markdown' {
  export * from '@contentful/rich-text-from-markdown/dist/types/index';
}
```

**Comment by erikthedeveloper** [comment]
I will confirm that @msholty-fd's suggestion above works great as expected! 👍 ❤️ 

I also confirmed that the upstream fix suggested by @teramotodaiki  adding `"typings"` property in `package.json` does the trick also:

![](https://cdn.zappy.app/c59b03f3a971337ac0408d1bf461f608.png)

I put a PR up for this now https://github.com/contentful/rich-text/pull/148

**Comment by magnattic** [comment]
This seems like an easy fix and a tiny PR. Could someone approve this? Would be much appreciated by everyone using typescript :)
