### ISSUE TITLE
@contentful/rich-text-react-renderer v14.1.0 is not on npm

### ISSUE THREAD

**Issue by zernie** [contentful/rich-text#139]
The latest version on npm is just 13.4.0

**Comment by 719media** [comment]
@DanweDE Can someone please address this? This is causing problems because rich-text-types 14.1.0 *is* published on npm, so when installing the latest libraries of both rich-text-html-renderer and rich-text-types for dependency sake, it's causing some real headaches.

**Comment by djagya** [comment]
Hi, sorry for the long wait. Now all v14.1.0 packages are published. Please let me know if the situation became better for you.

**Comment by dbartholomae** [comment]
When installing 14.1.0 it seems the dist folder is missing, making it unusable. Not sure if I have some caching issue or something, but 13.4.0 works fine, so maybe it has to do with the deploy

**Comment by djagya** [comment]
Taking a look.

**Comment by djagya** [comment]
Yeah, that's correct, because of some hiccups I published the package without the `dist` folder. I can't bump the version right now as I don't have the permissions yet. But don't worry, I'll fix it tomorrow ASAP.

**Comment by djagya** [comment]
Published `v14.1.1`, now with `dist` included! Please let me know if it fixes the issue.

**Comment by dbartholomae** [comment]
Thanks, works for me! :)
