### ISSUE TITLE
Embedded images in Richtext not appearing in JSON

### ISSUE THREAD

**Issue by KishokanthJeganathan** [contentful/rich-text#144]
Hi guys, 

I have some pics embedded in my rich text from contentful, but I am not seeing them

All I have under embedded-asset-block is the below

{
              "nodeType": "embedded-asset-block",
              "content": [],
              "data": {
                "target": {
                  "sys": {
                    "id": "c420V6OUhSdrfe73Hw6tQq0",
                    "type": "Link",
                    "linkType": "Asset",
                    "contentful_id": "420V6OUhSdrfe73Hw6tQq0"
                  }
                }
              }
            }

This issue was not present the first time I loaded the data. This occurred after I added some new content fields to the model and restarted the server. Can anyone help :/ I am really stumped

**Comment by iyubinest** [comment]
@KishokanthJeganathan how do you solved this?

**Comment by iyubinest** [comment]
I keep checking on this and I found a solution by deleting the `.cache` folder as is described [here](https://stackoverflow.com/a/55769299/2460590).

**Comment by KishokanthJeganathan** [comment]
@iyubinest Yep thats how I solved it as well buddy. gatsby clean did the trick :)
