### ISSUE TITLE
Dist Folder Missing from @contentful/rich-text-react-renderer 14.1.0

### ISSUE THREAD

**Issue by lisafolkerson** [contentful/rich-text#145]
Hi 👋 ! 

I think the dist folder is missing from the update @contentful/rich-text-react-renderer 14.1.0 earlier.

**Comment by pellelauritsen** [comment]
Got the same problem.

![image](https://user-images.githubusercontent.com/3658872/85339523-9eeb8600-b4e4-11ea-8524-4b2b2c5eab15.png)

**Comment by thomasbruketta** [comment]
+1 to the above. No dist folder in my npm module either.

**Comment by clockelliptic** [comment]
+1, same issue.

**Comment by sarah-j-smith** [comment]
Same.

Had to `npm install @contentful/rich-text-react-renderer@13.4.0 --save` because I was getting  Module not found errors.

**Comment by nbaosullivan** [comment]
v14.1.1 is out, see: https://github.com/contentful/rich-text/issues/139#issuecomment-647990143

**Comment by djagya** [comment]
I'm really sorry, there was a hiccup in the publishing process. `v14.1.1` fixes the problem as mentioned above, so I'll close this ticket. Feel free to reopen it if needed!
