### ISSUE TITLE
@contentful/contentful-slatejs-adapter removed from NPM

### ISSUE THREAD

**Issue by ayobami303** [contentful/rich-text#186]
@contentful/contentful-slatejs-adapter has been removed from npm and is breaking other packages that have it as a dependency.

https://www.npmjs.com/package/@contentful/contentful-slatejs-adapter

**Comment by djagya** [comment]
Thanks for reporting, looking into it now.

**Comment by djagya** [comment]
Ok, for some reason the package became private. I changed it back to public and will investigate the root cause.
