### ISSUE TITLE
Is there any options to add 'dropdown menu' inside the rich text editor?

### ISSUE THREAD

**Issue by ikhsanhabibi** [contentful/rich-text#188]
Hi! I want to add dropdown inside the rich text editor. WHow should it be? Can I custom the rich text editor using extension? or is there another option for doing it? Thanks!

![Capture](https://user-images.githubusercontent.com/33756873/98945275-98d95e80-24f2-11eb-87ab-a98d86cd49bd.JPG)

**Comment by YvesRijckaert** [comment]
Our field editors are open source so you can customise them to your needs.
See: https://www.contentful.com/developers/docs/extensibility/field-editors/example-customize-field-editor/
