### ISSUE TITLE
[rich-text-html-renderer] is there a htmlStringToDocument function?

### ISSUE THREAD

**Issue by iamrane** [contentful/rich-text#203]
Hi!
So nice that there is a documentToHtmlString function, but is there htmlStringToDocument function?

**Comment by OriginalEXE** [comment]
Hello,

It would not be as simple to support that given how open the HTML format is.

You could try achieving this through a combination of two libraries:

https://github.com/domchristie/turndown + https://github.com/contentful/rich-text/tree/master/packages/rich-text-from-markdown

This would, of course, require manual work for unsupported HTML nodes.
