### ISSUE TITLE
[rich-text-from-markdown][Bug] Vfile can't init because of process not defined

### ISSUE THREAD

**Issue by MaximeRougieux** [contentful/rich-text#204]
I'm trying to use this package in an Angular 11 app with npm and a call to the richTextFromMarkdown function throws an error :
![image](https://user-images.githubusercontent.com/73878075/109969472-3cde5400-7cf4-11eb-9c6a-8a80b00fe0d6.png)

After some researchs it seems to be related to the update of webpack to version 5 :
https://github.com/vfile/vfile/issues/38

Is anyone able to reproduce this ?

**Comment by DanweDE** [comment]
Hi @MaximeRougieux! I am closing the issue as it seems to be unrelated to the rich text package and specific to the tools you use. Feel free to reopen if you still require help or think there's anything we could do on our side.
