### ISSUE TITLE
404 error on npm install

### ISSUE THREAD

**Issue by fdmatte** [contentful/rich-text#226]
I am trying to use this package but when i try to npm install @contentful/contentful-slatejs-adapter i get this message.

`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@contentful%2fcontentful-slatejs-adapter - Not found
npm ERR! 404
npm ERR! 404  '@contentful/contentful-slatejs-adapter@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404`

can anyone help me with that?

**Comment by cleisti** [comment]
Also looking for help with this issue :)

**Comment by MelissaAlasalmi** [comment]
Same 🙏

**Comment by z0al** [comment]
Hey, thanks for reporting the issue. 

I just marked `@contentful/contentful-slatejs-adapter` as public again on npm so that should fix the issue. Meanwhile, I also have a PR open to mark it as public always.

Cheers
