### ISSUE TITLE
@rich-text-from-markdown: Issue with list parsing

### ISSUE THREAD

**Issue by ababol** [contentful/rich-text#25]
👋 Hello,

There is an issue if I want to parse markdown to rich-text. It is not outputing anything.
See: https://repl.it/repls/FatParallelTruetype to reproduce the issue

**Comment by Khaledgarbaya** [comment]
👋 @ababol,

This should be fixed in https://github.com/contentful/rich-text/pull/20
But I think we didn't release yet the package

Cheers,
Khaled

**Comment by ababol** [comment]
@Khaledgarbaya Yep it's working 👍 thanks
