### ISSUE TITLE
rich-text-react-renderer: Objects are not valid as a React child (found: object with keys {nodeType, content, data}). If you meant to render a collection of children, use an array instead.

### ISSUE THREAD

**Issue by macklark** [contentful/rich-text#277]
I have a problem while styling rich text using rich-text-types for my portfolio site

![code](https://user-images.githubusercontent.com/50847468/136668045-1992aaf0-2def-4ec2-b2ab-106b2f84c8c1.png)

Getting this error

![Capture](https://user-images.githubusercontent.com/50847468/136668086-a59c5289-98d9-4fe7-bf78-344591137e66.PNG)

Help me out!

**Comment by macklark** [comment]
oops my bad

**Comment by Psypher1** [comment]
> oops my bad

Can you please explain what you figured out? I am facing a similar problem on a project that was working before
