### ISSUE TITLE
rich-text-react-renderer - Avoid serving legacy JavaScript to modern browsers

### ISSUE THREAD

**Issue by jwugit** [contentful/rich-text#283]
While using documentToReactComponents rich-text-react-renderer, 
google page speed insights generate the following notice:

**Avoid serving legacy JavaScript to modern browsers**
```
Polyfills and transforms enable legacy browsers to use new JavaScript features. 
However, many aren't necessary for modern browsers. For your bundled JavaScript, 
adopt a modern script deployment strategy using module/nomodule feature detection 
to reduce the amount of code shipped to modern browsers, while retaining support for legacy browsers.
```
![image](https://user-images.githubusercontent.com/28541026/138737797-c0ba8241-0231-4833-94b2-7ad33033c880.png)

Probably not urgent, 
But is this something that will be updated in the near future, 

Thanks,

**Comment by z0al** [comment]
Thank you for the report. We are no longer bundling polyfills for `Object.values` or `Array.includes` since [v15.9.1](https://github.com/contentful/rich-text/pull/294/files#diff-9cbc0eb83214697c0b4de310dee54670e1b94250483d41dc1ae316f422d0f964)
