### ISSUE TITLE
dist folder missing on latest update

### ISSUE THREAD

**Issue by arzafran** [contentful/rich-text#285]
Hey! been using this package for a while now, never had any issues, but we updated the dependencies on a project and suddenly builds started to fail, noticed that the `v15.6.0` is missing the `dist` folder in `node_modules`:

<img width="236" alt="Screen Shot 2021-11-04 at 17 07 40" src="https://user-images.githubusercontent.com/466367/140413672-b8fbbf47-c560-463d-a506-c5ed78693ac8.png">

it's a Next.js 12 project using pnpm as package manager. the error happens on both     
`@contentful/rich-text-react-renderer` and `@contentful/rich-text-types`.

the temporary fix was to install `v15.5.x`

**Comment by acqhq** [comment]
Yes, I am getting same issue.

```
ModuleNotFoundError: Module not found: Error: Can't resolve '@contentful/rich-text-types' in '/vercel/path0/components/RichText'
--
```

**Comment by xmflsct** [comment]
Same

**Comment by jwugit** [comment]
same here

**Comment by snikch** [comment]
Seeing this across

```
@contentful/rich-text-react-renderer
@contentful/rich-text-types
@contentful/rich-text-plain-text-renderer
```
Unfortunately vercel doesn't appear to be caring about our `yarn.lock` so this has immediately caused our deploys to break 🤦

**Comment by alexshyba** [comment]
got broken too today :(

**Comment by master12** [comment]
@contentful/rich-text-plain-text-renderer failed

**Comment by arzafran** [comment]
Closing the issue, seems to be fixed with latest version.
