### ISSUE TITLE
Missing initializer in const declaration error when upgrading to version 15.9.1 with NextJS

### ISSUE THREAD

**Issue by AlexandraKlein** [contentful/rich-text#295]
When upgrading `rich-text-react-renderer` and `rich-text-types` from versions `15.5.1` to `15.9.1`, I get the following error on a NextJS production build on Vercel using GraphQL API:

`Uncaught SyntaxError: Missing initializer in const declaration`

The following, which comes from [ajv-validator](https://github.com/ajv-validator/ajv), seems to have the offending code: 

Minified:
```javascript
const c;
return x.str`must NOT have ${c} than ${b} items`
```
Unminified: 
```javascript
const error: KeywordErrorDefinition = {
  message({keyword, schemaCode}) {
    const comp = keyword === "maxItems" ? "more" : "fewer"
    return str`must NOT have ${comp} than ${schemaCode} items`
  },
  params: ({schemaCode}) => _`{limit: ${schemaCode}}`,
}
```

This dependency was added in this PR: [https://github.com/contentful/rich-text/pull/292](https://github.com/contentful/rich-text/pull/292)

**Comment by z0al** [comment]
Hey @AlexandraKlein, thanks for reporting the issue.

Can you please share a small repo with an example code to help me reproduce the issue?

**Comment by AlexandraKlein** [comment]
> Hey @AlexandraKlein, thanks for reporting the issue.
> 
> Can you please share a small repo with an example code to help me reproduce the issue?

Not very feasible for me at the moment. My repo is private and I don't have the time to clone and create a new Contentful space.

**Comment by mirshko** [comment]
I am also having this issue, only when running the build in production on latest Next.js and latest Contentful deps. 

https://github.com/mirshko/refuge-worldwide here is the site, currently going to revert back to pre this latest build to fix the issue.

**Comment by AlexandraKlein** [comment]
> I am also having this issue, only when running the build in production on latest Next.js and latest Contentful deps.
> 
> https://github.com/mirshko/refuge-worldwide here is the site, currently going to revert back to pre this latest build to fix the issue.

Hi @mirshko,

I reported this issue and share many dependencies with you. The following is my list. Wonder if this helps debug:

```json
    "@contentful/rich-text-react-renderer": "15.6.2",
    "@contentful/rich-text-types": "15.6.2",
    "body-scroll-lock": "^3.1.5",
    "classnames": "^2.3.1",
    "emailjs-com": "^3.2.0",
    "framer-motion": "^5.4.5",
    "google-map-react": "^2.1.10",
    "lodash-es": "^4.17.21",
    "next": "12.0.7",
    "qs": "^6.10.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-facebook-pixel": "^1.0.4",
    "react-hook-form": "^7.22.0",
    "react-lottie": "^1.2.3",
    "react-use": "^17.3.1",
    "remove-focus-outline": "^1.2.1",
    "sass": "^1.45.0",
    "smoothscroll-polyfill": "^0.4.4"
```

**Comment by AlexandraKlein** [comment]
Offending code: [https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/validation/limitProperties.ts#L7](https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/validation/limitProperties.ts#L7) or [https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/validation/limitItems.ts#L7](https://github.com/ajv-validator/ajv/blob/master/lib/vocabularies/validation/limitItems.ts#L7)
