### ISSUE TITLE
Only renders paragraphs in React?

### ISSUE THREAD

**Issue by a-tomlinson** [contentful/rich-text#30]
Am I doing something silly? Have the helper working and outputting HTML as a string, but there's no conversion of blocks that aren't paragraphs:

```import React from 'react';
import { documentToHtmlString } from '@contentful/rich-text-html-renderer';
// import styled from 'styled-components';

class RichTextRenderer extends React.Component {
  // eslint-disable-line react/prefer-stateless-function
  render() {
    const { content } = this.props;
    const article = documentToHtmlString(content);
    return <div dangerouslySetInnerHTML={{ __html: article }} />;
  }
}

RichTextRenderer.propTypes = {};

export default RichTextRenderer;
```
gives me the following output in browser and misses embedded assets entirely:

```
Christmas plans sorted? You’ll want our NYE guide: type: embedded-entry-inline id: 1ICVc1UQU8KiO8wuOqoOsc
```

**Comment by epegase** [comment]
Exact. All blocks, embedded-entry and assets don't render. I use a gatsby starter with my contentful account. It's only paragraph that render.

**Comment by Khaledgarbaya** [comment]
Hey @a-tomlinson,
You need to specify how you can render the embedded entry node

```
import { documentToHtmlString } from '@contentful/rich-text-html-renderer';
// import styled from 'styled-components';

const options = {
renderNode: {
  [INLINES.EMBEDDED_ENTRY]: node => {
              // you html code goes here
              return `<div class='custom-entry' />${
                node.data.target.fields.name['en-US']
              }</div>`
            },
  }
}
class RichTextRenderer extends React.Component {
  // eslint-disable-line react/prefer-stateless-function
  render() {
    const { content } = this.props;
    const article = documentToHtmlString(content, options);
    return <div dangerouslySetInnerHTML={{ __html: article }} />;
  }
}

RichTextRenderer.propTypes = {};

export default RichTextRenderer;
```

**Comment by codeithuman** [comment]
@Khaledgarbaya, is it possible to use a fluid `gatsby-image` component with `[BLOCKS.EMBEDDED_ENTRY]`?

I know fluid images have to use GraphQL. Would I need to use `allContentfulAsset` and then find the image that's passed into `[BLOCKS.EMBEDDED_ENTRY]` as `node`? Maybe use `<StaticQuery>` inside `renderNode`?

**Comment by jmdmacapagal** [comment]
@codeithuman have you solved the problem yet? I'm encountering this too, I cant seem to query the image for gatsby-image

**Comment by alejandronanez** [comment]
Hey @Khaledgarbaya, it seems that `node.data.target.fields` is no longer available. I'm not seeing it in the GraphQL response

![](https://cdn.zappy.app/18af1b26753332f55bdc05770e499883.png)

Since we can access `node.data.target.fields`, what would be the best way to render embedded entries?

**Comment by s4l4x** [comment]
I'm seeing this as well. No fields, just sys.

**Comment by s4l4x** [comment]
Possibly it's below the default link level of 1? 
https://www.contentful.com/developers/docs/concepts/links/
