### ISSUE TITLE
Bad mark types in README examples 

### ISSUE THREAD

**Issue by marconi1992** [contentful/rich-text#32]
Based on the tests the marks should contain a `type` property instead `nodeType`
https://github.com/contentful/rich-text/blob/master/packages/rich-text-html-renderer/src/__test__/documents/mark.ts

https://github.com/contentful/rich-text/blob/master/packages/rich-text-plain-text-renderer/README.md

![image](https://user-images.githubusercontent.com/11670923/49487969-58530f80-f80a-11e8-9023-93d8fee25ca9.png)

https://github.com/contentful/rich-text/blob/master/packages/rich-text-html-renderer/README.md
![image](https://user-images.githubusercontent.com/11670923/49487989-702a9380-f80a-11e8-8ae6-3088df0a0a56.png)

**Comment by cribbles** [comment]
Fixed in https://github.com/contentful/rich-text/pull/33. Thanks, @marconi1992!
