### ISSUE TITLE
gatsby-transformer-contentful-richtext doesn't work at all.

### ISSUE THREAD

**Issue by aofolts** [contentful/rich-text#36]
Not sure if it's just to ready yet, but `gatsby-transformer-contentful-richtext` doesn't work at all for me. I've tried it with several queries in graphql, and there are no errors, but no field for `childContentfulRichText` is added, either.

**Comment by aofolts** [comment]
I came back to Gatsby a couple hours later and `childContentRichText` is now magically working. So problem solved! ✨

**Comment by GarrettJMU** [comment]
Did you change anything in that time @aofolts ? I have not be able to get that field to access for me.

**Comment by Khaledgarbaya** [comment]
@GarrettJMU here is a sandbox example project with the plugin https://codesandbox.io/s/jljrl7z82w

**Comment by aofolts** [comment]
@GarrettJMU try deleting you `.cache` folder.
