### ISSUE TITLE
Missing default import in 'rich-text-types' modules.

### ISSUE THREAD

**Issue by felixdenoix** [contentful/rich-text#449]
The usage of the rich-text-types modules causes issues with Nuxt@^3 and its bundler, vite.

I've setup à reproduction repro [here](https://github.com/felixdenoix/contentful-nuxt-repro). Launching the dev task will greet you with the following error: 
```
500 The requested module '/_nuxt/node_modules/@contentful/rich-text-types/dist/index.js?v=d73224d7' does not provide an export named 'BLOCKS'
```

The issue related to the way the framework is using the same modules on the server and the client as explained [here](https://nuxt.com/docs/guide/concepts/esm#what-kinds-of-problems-can-there-be). 

I tried to tiknker with the rollup/ts configurations to make it work and propose a pr but without success.

Would you consider making the module compatible with ESM and CJS formats ? 

Regards and many thanks with the built modules.

Félix

**Comment by DalFanajin** [comment]
There's a bit more info on this issue as well as some workarounds here : [#395](https://github.com/contentful/rich-text/issues/395)
