### ISSUE TITLE
`documentToHtmlString`: JSON response have different nodeType's without 'INLINE'

### ISSUE THREAD

**Issue by MickL** [contentful/rich-text#452]
The [readme](https://github.com/contentful/rich-text/tree/master/packages/rich-text-html-renderer#usage) states rendering can be customized in the options of `documentToHtmlString()` like so:

```
      documentToHtmlString(response.data.mainpage.text.json, {
          renderNode: {
            ['BLOCKS.PARAGRAPH']: (node, next) => `1`,
            ['INLINES.HYPERLINK']: (node, next) => `2`,
          }
        })
```

However this doenst have any effect at all because the response of Contentful (I use GraphQL `entryName { json }`) returns different `nodeType`. The following works:

```
      documentToHtmlString(response.data.mainpage.text.json, {
          renderNode: {
            ['paragraph']: (node, next) => `1`,
            ['hyperlink']: (node, next) => `2`,
          }
        })
```

Not sure if this is related to you GraphQL API or if the readme is wrong

**Comment by samipe** [comment]
`['BLOCKS.PARAGRAPH']` should be `[BLOCKS.PARAGRAPH]`. It's imported from types and transpiles to `paragraph` etc
