### ISSUE TITLE
Next.js hydration error when using rich-text-react-renderer v.15.15.1 and higher

### ISSUE THREAD

**Issue by aladage** [contentful/rich-text#456]
I've been successfully using rich-text-react-renderer 15.12.1 in Next.js 12.3.4. However, when trying to upgrade to latest (or really any version higher than 15.12.1, I get an error that says "Error: Hydration failed because the initial UI does not match what was rendered on the server." Unfortunately I need to do this upgrade to gain support for superscript/subscript in Contentful rich text fields.

**Comment by xJkit** [comment]
Is there any possibilities that invalid HTML structure happens, such as `<div>` inside `<p>` tag? Because any normal text from the editor is treated as `<p>`, I think you can replace all of the p tag with `<div>` just like:

```js
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import { BLOCKS } from '@contentful/rich-text-types';

const renderOptions = {
  renderNode: {
      [BLOCKS.PARAGRAPH]: (node, children) => (
        <div className="paragraph">{children}</div>
      ),
    },
};

export default function RichTextRenderer({ document  }) {
  return documentToReactComponents(document, renderOptions)
}
```

**Comment by aladage** [comment]
Sorry, I actually worked with Contentful via a support ticket on this, and you're correct -- I believe my markup was invalid. I will close this issue. Thanks!
