### ISSUE TITLE
Partially bold words aren't being split correctly

### ISSUE THREAD

**Issue by JRebella** [contentful/rich-text#493]
When using [@contentful/rich-text-from-markdown](https://github.com/contentful/rich-text/tree/master/packages/rich-text-from-markdown) to convert markdown that contains a partially bold word like **Bold**Word, the bold portion is ignored and the markdown syntax is printed into the resulting paragraph as plain text as `__Bold__Word`

Italics on the other hand, work as expected and the part of the word which is marked as italic gets split into an _italic_ node

Example input markdown: 
```
*Italic* *Italic*Word /// __Bold__ __Bold__Word
```
Actual output
![image](https://github.com/contentful/rich-text/assets/47323512/621e2fc0-c320-49bd-b93a-98c6ab9c0869)

Expected output
![image](https://github.com/contentful/rich-text/assets/47323512/2cfa9789-aaef-4388-86db-a468bd90e818)

Output rich text nodes
![image](https://github.com/contentful/rich-text/assets/47323512/aed52b78-4126-4484-bf60-4d68e16d6416)

Notice how the last node in the array has the __ from markdown printed into plain text

**Comment by jdwillemse** [comment]
Using the ** notation for bold works e.g **Bold**Word

**Comment by colomolo** [comment]
Hello, this works according to specification of Commonmark thus not a bug.

See:
https://spec.commonmark.org/0.29/#example-385
https://spec.commonmark.org/0.29/#example-395
