### ISSUE TITLE
Astro component support

### ISSUE THREAD

**Issue by samaritanau** [contentful/rich-text#500]
Hello, we are writing an Astro site and want to create a "rich-text-astro-renderer". Does anyone know if that has been done yet?

**Comment by YvesRijckaert** [comment]
Hi @samaritanau 
I have not seen that before, can you help me understand what would make this renderer different from `rich-text-html-renderer`?
In the Astro docs it seems like they are using `rich-text-html-renderer`
https://docs.astro.build/en/guides/cms/contentful/#static-site-generation

**Comment by samaritanau** [comment]
Hi @YvesRijckaert ,

The html renderer just renders out html, however we need to render out Astro components, so we can get the functionality of the components. We have implemented this now with an Astro components that basically follows the patterns in the html renderer, seems to be working ok. I was going to submit a pull request, however I wasn't able to get it running in the code base. 

Cheers,
Henry

**Comment by ttntm** [comment]
Came across this issue (https://github.com/withastro/roadmap/issues/533) recently which could make it possible to use Astro components from within the HTML renderer in the future.

**Comment by samaritanau** [comment]
Just in case anyone is looking to do something similar here is the basic Astro file we went with to render Contentful RTE JSON into HTML and/or Astro components, the LinkWrapper component and Image component referenced are specific to our use case (locale support and some other things) so you'll need to roll your own, but you'll get the gist. Maybe this will help somebody looking to do what we needed to.

[RichTextAstroRenderer.zip](https://github.com/contentful/rich-text/files/13246159/RichTextAstroRenderer.zip)
