### ISSUE TITLE
Missing type for preserveWhitespace option @contentful/rich-text-react-renderer

### ISSUE THREAD

**Issue by roryhen** [contentful/rich-text#511]
I updated to version @contentful/rich-text-react-renderer@15.19.0 and I expected to be able to use the new `preserveWhitespace` option as it was added in https://github.com/contentful/rich-text/pull/497, but I think it's missing in the types since I get a typescript error:

![image](https://github.com/contentful/rich-text/assets/35480205/1fe9e52f-bf43-4e7d-9900-e159fd84106a)

**Comment by jesusvallez** [comment]
<img width="650" alt="image" src="https://github.com/contentful/rich-text/assets/19146593/f6645a3a-78df-4f52-83d0-3e75dfbbbf5a">

"@contentful/rich-text-react-renderer": "15.19.0",

It works perfectly for me, can you give more details?

**Comment by YvesRijckaert** [comment]
I also was not able to reproduce this. Can you reinstall your node modules / remove the cache and see if the problem persists?
