### ISSUE TITLE
&nbsp; is inserted as string, not as JSX character entity when using preserveWhitespace

### ISSUE THREAD

**Issue by andrewgul** [contentful/rich-text#514]
Let’s say I have text with multiple spaces: `multiple   spaces`.  Now `documentToReactComponents` (with `preserveWhitespace: true`) just replaces spaces with `&nbsp;`, and returns it as string, so I get: 

```tsx
'multiple&nbsp;&nbsp;&nbsp;spaces';
```

Since React does not recognize `&nbsp;` in string it renders it as is.

But I expect it to be turned into JSX:

```tsx
<>multiple&hbsp;&nbsp;&nbsp;spaces</>
```

There’s different behavior with line breaks, they are not inserted as strings, but replaced with JSX element `<br />`, so as result I get something like this:

```tsx
<p>
  {'multiple&nbsp;&nbsp;&nbsp;spaces'}
  <br />
  {'second&nbsp;&nbsp;&nbsp;line'}
</p>
```

I think, when I receive it as an argument in `renderNode` callback it should either be a string (not a `React.ReactNode`) so I can pass it to `dangerouslySetInnerHTML` to render markup properly:

```tsx
<p
  dangerouslySetInnerHTML={{ __html: 'multiple&nbsp;&nbsp;&nbsp;spaces<br />second&nbsp;&nbsp;&nbsp;line' }}
/>
```

or (a better solution in my opinion) both `&nbsp;` and `<br />` should be JSX:

```tsx
<p>
  multiple&nbsp;&nbsp;&nbsp;spaces
  <br />
  second&nbsp;&nbsp;&nbsp;line
</p>
```

**Comment by fafshari** [comment]
This is still an existing issue. I understand the test case presents that it's resolved, however in practice preserveWhitespace is rendering `&nbsp;` when more than one space is provided.
