### ISSUE TITLE
[Question] Rich text from HTML

### ISSUE THREAD

**Issue by sergey-hippo** [contentful/rich-text#516]
Currently, to convert HTML to rich text contentful users have 2 ways:
1. Convert HTML to markdown and then use official converter https://github.com/contentful/rich-text/tree/master/packages/rich-text-from-markdown
2. Use 3rd party poorly supported converter: https://github.com/sethimcclaine/contentful-html-rich-text-converter

What's the recommended solution and are there any plans to provide an official converter from HTML?

**Comment by colomolo** [comment]
Hello @sergey-hippo,
Unfortunately we don't have any recommended solution for this and no plans to add it so far. Does option 1 work for you?

**Comment by sergey-hippo** [comment]
Hi @colomolo! Yes, I went with option 1 and it works ok for me so far.
