### ISSUE TITLE
@contentful/rich-text-from-markdown Does not parse code blocks at all.

### ISSUE THREAD

**Issue by l-you** [contentful/rich-text#540]
Markdown parser does not work with code block at all.
## Reproduction
Create next.js app and use the following component.
```tsx
import { richTextFromMarkdown } from "@contentful/rich-text-from-markdown";
const code =  `
\`\`\`
some code
more <code></code>
function name(params:type) {
  
}
\`\`\`
    `
export default async function App() {
    const doc = await  richTextFromMarkdown(code)
    return (
        <div>
            {JSON.stringify(doc)}
        </div>
    );
}
```

Output of that is `{"nodeType":"document","data":{},"content":[]}` instead of node with a code block.
Is it expected behaviour?
I can write code with \`\` syntax, but what should I do when I need multiline code block?

**Comment by YvesRijckaert** [comment]
Hey! Thanks for your comment. Our rich text editor does not support a multiline code block yet, we only support code inlines
