### ISSUE TITLE
documentToHtmlString does not acknowledge nodeType: embedded-asset-block

### ISSUE THREAD

**Issue by sethimcclaine** [contentful/rich-text#58]
embedding images into rich text does not seem to be handled by documentToHtmlString.

nodeType comes across as `embedded-asset-block` for images

      {  
         "data":{  
            "target":{  
               "sys":{  
                  "space":{  
                     "sys":{  
                        "type":"Link",
                        "linkType":"Space",
                        "id":"gedg1u5b0yz9"
                     }
                  },
                  "id":"2CzKe2pWvewCiek6w0yyoQ",
                  "type":"Asset",
                  "createdAt":"2019-01-07T22:37:55.473Z",
                  "updatedAt":"2019-01-07T22:37:55.473Z",
                  "environment":{  
                     "sys":{  
                        "id":"master",
                        "type":"Link",
                        "linkType":"Environment"
                     }
                  },
                  "revision":1,
                  "locale":"en-US"
               },
               "fields":{  
                  "title":"Test Image",
                  "description":"Image for testing",
                  "file":{  
                     "url":"//images.ctfassets.net/<hidden>/<hidden>/<hidden>/IMG_2878.JPG",
                     "details":{  
                        "size":3874595,
                        "image":{  
                           "width":5184,
                           "height":3456
                        }
                     },
                     "fileName":"IMG_2878.JPG",
                     "contentType":"image/jpeg"
                  }
               }
            }
         },
         "content":[],
         "nodeType":"embedded-asset-block"
      },

Is this already possible, or is this a feature request (or possibly even a bug)?

**Comment by Khaledgarbaya** [comment]
Hey @sethimcclaine 
You need to specify how to render that 
You can find more about it here https://github.com/contentful/rich-text/tree/master/packages/rich-text-html-renderer#usage
```js
const options = {
  renderNode: {
    [BLOCKS.EMBEDDED_ENTRY]: (node) => `<custom-component>${customComponentRenderer(node)}</custom-component>`
  }
}

documentToHtmlString(document, options);
```

**Comment by sethimcclaine** [comment]
Thank you @Khaledgarbaya!

**Comment by aepp** [comment]
@Khaledgarbaya there is no **fields** field in **target** anymore:

<img width="729" alt="no_fields" src="https://user-images.githubusercontent.com/5745874/67024592-f723ea00-f104-11e9-9ad5-a6cad5046f4b.png">

instead, there is a field called **includes** next to **items** field:

<img width="802" alt="includes_instead" src="https://user-images.githubusercontent.com/5745874/67024737-318d8700-f105-11e9-8364-ee7e99a15bc8.png">


How is it supposed to be done now?

**Comment by AbePralle** [comment]
> @Khaledgarbaya there is no **fields** field in **target** anymore:
> 
> How is it supposed to be done now?

I ran into the same issue. Here is my solution: https://stackoverflow.com/a/77498343/135791
