### ISSUE TITLE
gatsby-transformer-contentful-richtext returning null

### ISSUE THREAD

**Issue by mirshko** [contentful/rich-text#62]
hey there! 

when doing a standard query its seeming that a certain block of an h1 and an embeded entry are returning `null` as the html value.

```
"block3": {
  "childContentfulRichText": {
    "html": null
  }
}
```

**Comment by mirshko** [comment]
upon further research this seems to be coming from rich text fields in Contentful with an empty space / block under a node based item either an embed, styled text type, or bullets. unless i clear the gatsby cache and reimport it fails on running the import of contentful data

**Comment by sbezludny** [comment]
Hey @mirshko,
we've deprecated `gatsby-transformer-contentful-richtext` in favour of `gatsby-source-contentful` and `@contentful/rich-text-react-renderer` packages
https://www.gatsbyjs.org/packages/gatsby-source-contentful/?=gatsby-transformer-contentful-richtext#contentful-rich-text

Please let me know if I can do anything to help.
