### ISSUE TITLE
Rich text with link as a first element fails to render first paragraph.

### ISSUE THREAD

**Issue by jporwol** [contentful/rich-text#659]
When we created rich text entry with link as a first element - rich text renderer for some reason fails to render the whole first paragraph. Our custom rednder options are not triggered at all, no errors are reported or anything, it just misses it.

**Comment by z0al** [comment]
Hey @jporwol , could you please provide a minimal reproduction code snippet to help debug this?

**Comment by jporwol** [comment]
Argh, forgot to update this here! Sorry.
Turns out the issue is with our code in the end, just not where I was looking and could not figure it out. My bad for creating this issue before I finished investigation, and even more - for not closing it. Sorry!

Seems like contentful rich text renderer is doing a fine job converting stuff, thanks for that!
