### ISSUE TITLE
\n is not converted to <br /> in rich-text-html-renderer

### ISSUE THREAD

**Issue by marcneander** [contentful/rich-text#69]
So I noticed that doing `shift + enter` in a richtext editor will not give me a `<br>` after running it through `rich-text-html-renderer`.

Not sure if it's by design. And if so, I'd like to know the best way around it since there is not a good way to custom render normal text it seems like?

https://github.com/contentful/rich-text/blob/master/packages/rich-text-html-renderer/src/index.ts#L102

**Comment by mgmolisani** [comment]
Don't overthink it mate. `documentToHtmlString` just returns a string. You can easily just call:

``` javascript
documentToHtmlString(someRichText).replace(/\n/g, `</br>`);
```

Alternatively, escape only runs after the node has been processed so you can pass a custom renderer where you need this behavior in specific nodes in the following way:

``` javascript 
{
  renderNode: {
    ["paragraph"]: (node, next) => `<p>${next(node.content).replace(/\n/g, `</br>`)}</p>`
  }
}
```

which would provide this behavior only in paragraph tags.

**Comment by schoenwaldnils** [comment]
The replace would escape the `<br />` in my case.

```css
p {
  white-space: pre-wrap;
}
```
solved it for me
