### ISSUE TITLE
Convert rich text to markdown

### ISSUE THREAD

**Issue by cajoy** [contentful/rich-text#86]
I know there is a way to convert markdown to rich text?

But also I need to convert rich text to markdown. Is there any way to do that?

**Comment by sbezludny** [comment]
Hi @cajoy,
atm, we do not offer dedicated tooling for converting rich-text to markdown. 
But `@contentful/rich-text-html-renderer` should be flexible enough to be used for generating markdown output.

e.g.
```js
import { MARKS, BLOCKS } from "@contentful/rich-text-types";
import { documentToHtmlString } from "@contentful/rich-text-html-renderer";

documentToHtmlString(doc, {
  renderMark: {
    [MARKS.BOLD]: text => `*${text}*`,
    [MARKS.ITALIC]: text => `_${text}_`
  },
  renderNode: {
    [BLOCKS.HEADING_1]: (node, next) => `# ${next(node.content)}`
  }
});

/*
*Hello*_ world!_

# Heading
*/
```

See the following sandbox example for more details:
https://codesandbox.io/s/jj1mj3zw0v


Please let me know if this helps.

**Comment by cajoy** [comment]
Thank you . I will try it

**Comment by davidsoderberg** [comment]
Hi how can I see if the list item is ordered or unordered so I can parse it to markdown?
