### ISSUE TITLE
React: Disable BLOCKS.PARAGRAPH styling when having styling setup up for MARKS.CODE

### ISSUE THREAD

**Issue by marcuszierke** [contentful/rich-text#88]
Hey guys,

I can't imagine that this hasen't been covered yet but I didn't find anything in the docs so my questions is: if you have a styling set up for the BLOCKS.PARAGRAPH how can you disable that if you have something set up for MARKS.CODE as well? 

Any workaround for that? We are talking about `documentToReactComponents`. Thanks a lot!

**Comment by mgmolisani** [comment]
You could handle it in two ways IMO. Comes down to preference. A) Recursively adjust the document tree before passing it to the renderer to replace paragraph nodes that contain text with code marks to just the inner content node. B) Paragraph renderer takes the raw node as an arg so you could write a conditional on that node.content to render a paragraph tag if the content is not text with code and a fragment if it is a text node with code. The second is significantly easier.

**Comment by marcuszierke** [comment]
Thanks for the reply, @mgmolisani but the problem seems to be a different one because somehow it's still adding the `blogpost-text` to the `blogpost-code-snippet` class (see below).

Definition of my options:

<img width="787" alt="Screenshot 2019-04-17 at 14 47 31" src="https://user-images.githubusercontent.com/23409802/56288958-2179f800-6120-11e9-92e3-f3bbed83f5bf.png">

Inspect of the `blockquote` class:

<img width="517" alt="Screenshot 2019-04-17 at 14 47 47" src="https://user-images.githubusercontent.com/23409802/56288998-39517c00-6120-11e9-86f0-ea34bb2d3e0a.png">

Inspect of the `code` class:

<img width="398" alt="Screenshot 2019-04-17 at 14 48 14" src="https://user-images.githubusercontent.com/23409802/56289053-58e8a480-6120-11e9-8a1a-aaf8797ea76d.png">

Is there any other workaround for this / anything in the docs that helps?

**Comment by mgmolisani** [comment]
I don't see where in your code you are handling the difference between a paragraph with a code node and a paragraph without a code node.  There should be a conditional in the paragraph renderer body to decide if the wrapper is a `<div>` or a `<Fragment>`. Assuming you were intending to go with option B. If you went with A, I can't tell how you reworked the tree with the provided snippet.

**Comment by mgmolisani** [comment]
Try this in place of your current renderer for paragraphs. This is what I was suggesting before. I did not test this but the idea is if the current paragraph node has any child (should only be one child anyway) this is a text node and if that text node has a code mark, render a fragment, otherwise, a div.

```jsx
[BLOCKS.PARAGRAPH]: (node, children) => node.content.some(childNode => childNode.nodeType === `text` && childNode.marks.some(mark => mark.type === MARKS.CODE)) ? <>{children}</> : <div className="blogpost-text">{children}</div>
```

**Comment by sbezludny** [comment]
> because somehow it's still adding the blogpost-text to the blogpost-code-snippet class 

This is the expected behaviour since `code` (MARKS.CODE) is a formatting mark that is associated with characters in the paragraph node. 
From what it seems you're implementing a code **block**, do I understand correctly?

**Comment by mgmolisani** [comment]
Repeat the same approach but in your blockquote renderer to filter out if the child node is a paragraph.

```jsx
[BLOCKS.QUOTE]: (node, children) => node.content.some(childNode => childNode.nodeType === BLOCKS.PARAGRAPH) ? children : /* Default goes here*/
```

If I remember the types correctly though, blockquote should be a top level block so you might want to check your actual content for why a paragraph is getting created on the inner node. Might be how the content was entered in the editor.

**Comment by mgmolisani** [comment]
If you want to get crazy here, remember you get a full node in each renderer and nodes can be passed as documents to `documentToReactComponents` so instead of using `children` in `<div>{children}</dvi>`, you could instead write `<div>{documentToReactComponents(node, quoteSpecificOptions)}<div>`. How fun is that!

**Comment by marcuszierke** [comment]
> If I remember the types correctly though, blockquote should be a top level block so you might want to check your actual content for why a paragraph is getting created on the inner node. Might be how the content was entered in the editor.
> 
> Edit : I misunderstood what you were trying to do. To change the children that render in a block, I would recommend using the React.Children helpers to alter your children and remove the paragraph wrappers. You can also go with the other approach of altering the tree before passing it.
> 
> Second edit: Blockquote content is always a paragraph array per the type.

I just those this in the docs as well (line 51): https://github.com/contentful/rich-text/blob/master/packages/rich-text-types/src/schemaConstraints.ts#L42

So bottom line I guess there is no way to change the default?

**Comment by mgmolisani** [comment]
I would use my second suggestion and instead of using `children` use `documentToReactComponents` on the `node` with a new option set. Shared options can be declared separately and spread onto both option sets. This actually gets me thinking about some possible improvements to the React (and other) renders to not be specific to the Document type and instead work for any Node.

**Comment by sbezludny** [comment]
@marcuszierke if you want to apply different styles to the paragraphs depending on their content, you could use embedded entries and specify rendering rules depending on their content type. e.g.

```jsx
{documentToReactComponents(richTextDoc, {
        renderNode: {
          "embedded-entry-block": (node, next) => {
            const entry = node.data.target
            const contentType = node.data.target.sys.contentType.sys.id

            switch (contentType) {
              case "codeBlock":
                return <pre>{entry.fields.swift["en-US"]}</pre>

              case "lesson":
                return <p className="blogpost-content">{documentToReactComponents(entry.fields.copy["en-US"], {/*renderers for embedded content*/})}</p>

              default:
                return null
            }
          },
        },
        renderMark: {
          bold: text => <b style={{ color: "red" }}>{text}</b>,
        },
      })}

```

**Comment by marcuszierke** [comment]
Thanks for all the hints, guys! I think I found a good workaround by just chaining the according css-classes which helped to solve the problem without going crazy within the `MARKS` and `BLOCKS` syntax.
