### ISSUE TITLE
Suggestion: richTextTo... instead of documentTo...

### ISSUE THREAD

**Issue by mgmolisani** [contentful/rich-text#89]
While trying to assist with #88, I made a suggestion to call `documentToReactComponents` inside a renderer passed to `documentToReactComponents`. This works but is in conflict with how the renderers are designed which is to take in a node of type `Document`. It got me wondering why this is suggesting that the renderer can only take a Document as an argument since the renderer itself is made of only two functions where both do not care if the the argument is itself a Node or a Document Node.

In explanation, `documentToReactComponents` takes a Document, passes its content if it has it to `nodeListToReactComponents`, which then calls `nodeToReactComponent` on the elements of the content array. Basically, `documentToReactComponents` sets up the default options, `nodeListToReactComponents` middle mans the call to `nodeToReactComponent`, and `nodeToReactComponent` handles the rest. `nodeToReactComponent` handles any type of Node so realistically, so could `documentToReactComponents`.

## This brings me to my suggestion:

1. Implement `richTextToReactComponents` (and its equivalents) which takes any rich text Node and Options and sets up meaningful default options. Same signature as `documentToReactComponents` but with Node instead of Document. First call internally is to `nodeToReactComponent` instead of `nodeListToReactComponents`. It may be better as it is, however. Discussion below.
2. Deprecate the `documentToReactComponents` (and its equivalents) -  `richTextToReactComponents` takes over the same functionality so this is essentially a name change. Could also just export `richTextToReactComponents` aliased as  `documentToReactComponents` as a stop-gap.

## This has a few benefits:

1. Name describes the intent - no longer suggests a Document is required.
2. Allows for rendering of text nodes as Documents which currently is not possible as it has no content field. Remains backwards compatible. I can't think of a really good reason for this. Not sure why you'd utilize the whole renderer just for a simple text node, but currently you can't so...
3. Clearer understanding when calling inside of another call to `richTextToReactComponents` (related to benefit 1 and explained further below).
4. Won't break when using Typescript - Document = Node : Node != Document

A use case for this change is allowing for sub-renderers. I'm sure a ton of thought went into the semantics of the rich text editor output but sometimes it can be too constraining such as putting a `<p>` tag directly inside a `<blockquote>` or `<li>`. Because we only have access to the node and its children, not its parent, we can't make the determination whether or not the `<p>` tag is desired or not based on what it's wrapped in and it is harder to remove from the parent than in is in the renderer for that node. With sub renderers, we can decide easily in the parent how we render its specific children.

### Notes on backwards compatibility:
The React renderer purposely renders unknown marks as `<>{children}</>` (although this could also be updated to just `children` as it would be a valid ReactNode on its own). This makes unknowns basically passthrough. This is how the renderer would now handle the `BLOCKS.DOCUMENT` nodeType in the new implementation basically ignoring it and moving on to its children.

```jsx
    const children: ReactNode = nodeListToReactComponents(node.content, options);
    if (!node.nodeType || !renderNode[node.nodeType]) {
      return <>{children}</>;
    }
    return renderNode[node.nodeType](node, children);
```

The HTML renderer unfortunately renders empty strings on unknowns. This is in part because it API is more complicated using a `next` callback (which could be changed to work like the React version). The default should, instead of an empty string, be `nextNode(node.content)` to passthrough the bad mark instead of bailing entirely (which is what it would do with `BLOCK.DOCUMENT` if it wasn't changed).

If making that breaking change (marked as a TODO still so maybe now it's time to do!), an alternative is to add `BLOCKS.DOCUMENT` as a renderable mark that has the passthrough behavior by default (this could also be hard coded as overwriting it may not be intentional via the Options arg). It may also be better to leave the top level block out of the rendered output as it currently works. This means barely anything changes other than the signature of the function to be `Block | Inline`, but also means we can't use `Text` as an argument. Again, having `Text` as an arg doesn't seem that important as I can't think of a use case. Omitting the top level block also make composing sub-renderers easier as those paying attention would recognize a call to `richTextToReactComponents(node)` in the callback would rerender the node in the node so you would actually have to either return `richTextToReactComponents(node, options)` in the callback and pass a custom renderer for the calling nodeType (not intuitive) or call `node.content.map(child => richTextToReactComponents(node))` which is much more difficult. I also believe that approach would require a wrapper to add keys. Doubly frustrating. I will leave it to discussion what matches the intent of the renderer better.

Sorry for continuing to try to make edits to these libs. I just really like working on this project and feel comfortable with this codebase and the Contentful rich text team here!

@connor-baer 
@Khaledgarbaya

**Comment by mgmolisani** [comment]
This actually got me thinking further. There is certainly a way to make a sufficiently generic renderer that can handle cases of an output of plain text, HTML, or React components as well as any other custom render (Vue comes to mind). The generic renderer could then be extended with defaults for all three existing renderers with similar APIs to the current iterations. This would make updates to the rich text tree structure trivial for all renderers. I already have a prototype going on something that could do this.

**Comment by sbezludny** [comment]
Thanks for such a detailed proposal.
I like the idea of changing argument type from Document to Node in `documentToReactComponents` and I think we can do it now, without introducing a breaking change.

As for renaming/deprecating existing methods, I'd be against implementing them right now, as we want to gather more feedback and pain points before introducing breaking changes.

**Comment by mgmolisani** [comment]
Changing to Node would include Text so a union type ContentNode = Block | Inline would probably fit the current model better even though Text would bail out and return `null` anyway since there is a check for `content`. I think that change is definitely good for the TS folks.

Aside from the suggested change in the HTML renderer marked as a TODO, my suggestions would all be backwards compatible and the rename could be handled with an alias both using `richTextToReactComponents` under the hood.

I definitely will keep playing with the idea of a single renderer in my own time since I think it's a fun challenge.

**Comment by ryb73** [comment]
Hey @mgmolisani. I see this was closed as completed – are you able to speak to what the accepted solution was? As far as I can tell only `Document`s are renderable (at least in rich-text-react-renderer which is what I'm using)
